version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: myapp # Optional: creates a default database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/myapp
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    working_dir: /app
    command: npm run dev
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
