services:
  app:
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:123456@postgres:5432/tired
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tired
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge